### PR TITLE
Feature: support webview style

### PR DESCRIPTION
**Pull request by 77xi**
eg: 

```js
style={{
     backgroundColor: "transparent"
}}
```

### CODE REVIEW

**Comment by sebastianbochan** [comment]
Hi @77xi,
Thank you for the PR, will merge it next week (need add some docs about).

**Comment by 77xi** [comment]
> Hi @77xi,
> Thank you for the PR, will merge it next week (need add some docs about).

https://github.com/highcharts/highcharts-react-native/pull/41  😉😉😉😉

**Comment by sebastianbochan** [comment]
Thank you for the additional PR.

**Comment by Samoy** [comment]
> > Hi @77xi,
> > Thank you for the PR, will merge it next week (need add some docs about).
> 
> #41 😉😉😉😉

Hope to deal it as soon as possible. Thanks very much.

**Comment by sebastianbochan** [comment]
I released new version 2.1.1, where your commit is added (due to merge conflicts its not visible here)

**Pull request closed without merging**
