### PR TITLE
Add annotations module to project

### PR DESCRIPTION
**Pull request by brunobc182**
# What

This __PR__ adds the `annotations` module to project.

# Why

We need this modules to use [annotations](https://api.highcharts.com/highcharts/annotations) from `Highcharts.chart`

### CODE REVIEW

**Comment by sebastianbochan** [comment]
The reason of not added annotaitons module is missing full compatibility with touch devices. So at this moment I will not merge it until add full touch support of annotations.

**Comment by brunobc182** [comment]
> The reason of not added annotaitons module is missing full compatibility with touch devices. So at this moment I will not merge it until add full touch support of annotations.

Is there other way to make an annotations or something like that? Something that i mark a point on chart and show some label or information.

**Comment by sebastianbochan** [comment]
Well, you can try to use mentioned annotations, but be aware of limits. Maybe in your scenario its enough.

ps. You can try to use renderer to add custom shape by a label options.
Docs:
- https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#label

**Comment by gezichenshan** [comment]
@sebastianbochan But how to do this programmatically call within this react chart component?

**Comment by gezichenshan** [comment]
For those may need same help: 
I added a ref to HighchartsReactNative,
chart = chartRef.current.webviewRef
and then call chart.injectJavaScript method to do the job.

Note the chartRef.current.webviewRef might be null, so you should make sure the chart is successfully loaded.

```
<HighchartsReactNative
        ref={chartRef}
>
</HighchartsReactNative>

const run = `
              if(window.Highcharts.charts.length > 0){
                const chart = window.Highcharts.charts[0]
                var point = chart.series[0].points[${alertLabelInDataIndex}];
                const chartWidth = chart.chartWidth
                const html = '<div style="z-index:-1"><div>${dayjs(alert.eventDate).format(
                  'DD/MM HH:mm',
                )}</div><div>Battery: ${alertBatteryLevel}</div></div>'
                const labelString = 'Battery: ${alertBatteryLevel}'
                let labelX = point.plotX
                if(point.plotX + 80 > chartWidth){
                  labelX = chartWidth -80
                }
                if(point.plotX - 80 < 0){
                  labelX = 0
                }
                window.alertLabel = chart.renderer.label(html, labelX, point.plotY-10, 'callout', point.plotX + chart.plotLeft, point.plotY + chart.plotTop + 10, true)
                    .css({
                        color: '#FFFFFF'
                    })
                    .attr({
                        fill: 'rgba(255, 0, 0, 0.75)',
                        padding: 8,
                        r: 5,
                        zIndex: 6
                    })
                    .add();
              }
              true;
            `;
  chart.injectJavaScript(run);
```

**Comment by Denyllon** [comment]
Closed due to inactivity.

**Pull request closed without merging**
